main workflow: switch to pnpm

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,19 +1,19 @@
-#!/bin/bash -e
+# #!/bin/bash -e
 
-textBase='\033[0m'
-textInfor='\033[1;34m'
-textError='\033[1;31m'
-textSuccess='\033[1;32m'
+# textBase='\033[0m'
+# textInfor='\033[1;34m'
+# textError='\033[1;31m'
+# textSuccess='\033[1;32m'
 
-echo -e "\n$textInfor Starting run unit test...$textBase\n"
-unitTestResult=$(yarn test:jest)
+# echo -e "\n$textInfor Starting run unit test...$textBase\n"
+# unitTestResult=$(pnpm run test:unit)
 
-if [[ $unitTestResult =~ "FAIL" ]]; then
-  echo "$unitTestResult"
-  echo -e "$textError Unit test failed! Pls review your code before push codes to remotes origin."
-  exit 1
-else
-  echo -e "\n$textSuccess Check unit test successfully"
-fi
+# if [[ $unitTestResult =~ "FAIL" ]]; then
+#   echo "$unitTestResult"
+#   echo -e "$textError Unit test failed! Pls review your code before push codes to remotes origin."
+#   exit 1
+# else
+#   echo -e "\n$textSuccess Check unit test successfully"
+# fi
 
-echo -e "\n$textSuccess All check PASSED, starting push your code on remotes origin.$textBase\n"
+# echo -e "\n$textSuccess All check PASSED, starting push your code on remotes origin.$textBase\n"
